/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Ping;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-04-16T14:12:26.096Z")

@Api(value = "ping", description = "the ping API")
public interface PingApi {

    @ApiOperation(value = "Say Hello World", nickname = "getPing", notes = "", response = Ping.class, authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:pets", description = "modify pets in your account"),
            @AuthorizationScope(scope = "read:pets", description = "read your pets")
            })
    }, tags={ "ping", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Ping.class),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/ping",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Ping> getPing();


    @ApiOperation(value = "Add a new message", nickname = "postPing", notes = "", response = Ping.class, authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:pets", description = "modify pets in your account"),
            @AuthorizationScope(scope = "read:pets", description = "read your pets")
            })
    }, tags={ "ping", })
    @ApiResponses(value = { 
		@ApiResponse(code = 201, message = "Successfully created", response = Ping.class),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/ping",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Ping> postPing(@ApiParam(value = "Message to print" ,required=true )  @Valid @RequestBody Ping body);

}
