language: java
script:
- cp $HOME/.m2/repository/io/swagger/swagger-spring/1.0.0/swagger-spring-1.0.0.jar .
- ls /home/travis/build/agarwalgarima90/spring
- docker build -t gagarwal90/myapp:v2 .
- docker image list
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push gagarwal90/myapp:v2
- docker run -p 8080:8080 -d gagarwal90/myapp:v2
- echo "Sleeping for 5 sec"; sleep 5
- echo "Woke up from sleep"
- docker ps
- iptables -L
- ./integrationTestSuite.sh
#- "curl -X GET --header 'Accept: application/json' 'http://127.0.0.1:8080/v2/ping'"
- docker stop `docker ps | grep 'gagarwal90/myapp:v' | awk '{print $1}'`
